inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - '**/Rakefile'
    - '**/Gemfile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'vendor/**/*'
    - 'Guardfile'
  RunRailsCops: true
  DisplayCopNames: true

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false
