# Only maintaining this file because the Rails server falls over
# if these keys are not present.  **NEVER** use these keys for anything.

development:
  secret_key_base: A-REALLY-LONG-SECRET-KEY

test:
  secret_key_base: A-REALLY-LONG-SECRET-KEY

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
